adapter: table30v2
config:
  module: data_configs.config_table30v2_dataset
  getter: get_dataset_config
  key: ur5
  aligned_key: ur5_urdf_v2

arms:
  - arm_link_keys:
      - shoulder_link
      - upper_arm_link
      - forearm_link
      - wrist_1_link
      - wrist_2_link
      - wrist_3_link
    ee:
      parent: wrist_3_link
      rotate_z_deg: 0
      gripper_forward: 0.236

camera_references:
  - tool0
