adapter: rh20t
config:
  module: data_configs.config_rh20t_dataset
  getter: get_kinematics_config
  key: flexiv
  aligned_key: flexiv_urdf_v2

arms:
  - arm_link_keys:
      - link1
      - link2
      - link3
      - link4
      - link5
      - link6
      - link7
    ee:
      parent: link7
      rotate_z_deg: 90
      gripper_forward: 0.28286744101103084

camera_references: []
